name: ussc
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14.3
  - pandas
  - scikit-learn
  - statsmodels
  - plotly
  - matplotlib
  - seaborn
  # - ejolly::pymer4 = # mixed effects model library
  - requests
  - geopandas
  - jupyter
  - polars
  - gdown