

"""
A script for storing all large mappings used in the project along with functions to apply the mappings
"""

COUNTY_DIST_XREF_MAP = district_replace = {
    'Alabama, Southern': 'Southern District of Alabama',
    'Alabama, Northern': 'Northern District of Alabama',
    'Alabama, Middle': 'Middle District of Alabama',
    'Alaska, Alaska': 'District of Alaska',
    'Arizona, Arizona': 'District of Arizona',
    'Arkansas, Eastern': 'Eastern District of Arkansas',
    'Arkansas, Western': 'Western District of Arkansas',
    'California, Northern': 'Northern District of California',
    'California, Eastern': 'Eastern District of California',
    'California, Central': 'Central District of California',
    'California, Southern': 'Southern District of California',
    'Colorado, Colorado': 'District of Colorado',
    'Connecticut, Connecticut': 'District of Connecticut',
    'Delaware, Delaware': 'District of Delaware',
    'District of Columbia, District of Columbia': 'District of District of Columbia',
    'Florida, Northern': 'Northern District of Florida',
    'Florida, Middle': 'Middle District of Florida',
    'Florida, Southern': 'Southern District of Florida',
    'Georgia, Middle': 'Middle District of Georgia',
    'Georgia, Southern': 'Southern District of Georgia',
    'Georgia, Northern': 'Northern District of Georgia',
    'Hawaii, Hawaii': 'District of Hawaii',
    'Idaho, Idaho': 'District of Idaho',
    'Illinois, Southern': 'Southern District of Illinois',
    'Illinois, Central': 'Central District of Illinois',
    'Illinois, Northern': 'Northern District of Illinois',
    'Indiana, Southern': 'Southern District of Indiana',
    'Indiana, Northern': 'Northern District of Indiana',
    'Iowa, Southern': 'Southern District of Iowa',
    'Iowa, Northern': 'Northern District of Iowa',
    'Kansas, Kansas': 'District of Kansas',
    'Kentucky, Western': 'Western District of Kentucky',
    'Kentucky, Eastern': 'Eastern District of Kentucky',
    'Louisiana, Western': 'Western District of Louisiana',
    'Louisiana, Eastern': 'Eastern District of Louisiana',
    'Louisiana, Middle': 'Middle District of Louisiana',
    'Maine, Maine': 'District of Maine',
    'Maryland, Maryland': 'District of Maryland',
    'Massachusetts, Massachusetts': 'District of Massachusetts',
    'Michigan, Eastern': 'Eastern District of Michigan',
    'Michigan, Western': 'Western District of Michigan',
    'Minnesota, Minnesota': 'District of Minnesota',
    'Mississippi, northern': 'Northern District of Mississippi',
    'Mississippi, southern': 'Southern District of Mississippi',
    'Missouri, Western': 'Western District of Missouri',
    'Missouri, Eastern': 'Eastern District of Missouri',
    'Montana, Montana': 'District of Montana',
    'Nebraska, Nebraska': 'District of Nebraska',
    'Nevada, Nevada': 'District of Nevada',
    'New Hampshire, New Hampshire': 'District of New Hampshire',
    'New Jersey, New Jersey': 'District of New Jersey',
    'New Mexico, New Mexico': 'District of New Mexico',
    'New York, Northern': 'Northern District of New York',
    'New York, Western': 'Western District of New York',
    'New York, Southern': 'Southern District of New York',
    'New York, Eastern': 'Eastern District of New York',
    'North Carolina, Western': 'Western District of North Carolina',
    'North Carolina, Eastern': 'Eastern District of North Carolina',
    'North Carolina, Middle': 'Middle District of North Carolina',
    'North Dakota, North Dakota': 'District of North Dakota',
    'Ohio, Southern': 'Southern District of Ohio',
    'Ohio, Northern': 'Northern District of Ohio',
    'Oklahoma, Eastern': 'Eastern District of Oklahoma',
    'Oklahoma, Western': 'Western District of Oklahoma',
    'Oklahoma, Northern': 'Northern District of Oklahoma',
    'Oregon, Oregon': 'District of Oregon',
    'Pennsylvania, Eastern': 'Eastern District of Pennsylvania',
    'Pennsylvania, Middle': 'Middle District of Pennsylvania',
    'Pennsylvania, Western': 'Western District of Pennsylvania',
    'Puerto Rico, Puerto Rico': 'District of Puerto Rico',
    'Rhode Island, Rhode Island': 'District of Rhode Island',
    'South Carolina, South Carolina': 'District of South Carolina',
    'South Dakota, South Dakota': 'District of South Dakota',
    'Tennessee, Middle': 'Middle District of Tennessee',
    'Tennessee, Eastern': 'Eastern District of Tennessee',
    'Tennessee, Western': 'Western District of Tennessee',
    'Texas, Southern': 'Southern District of Texas',
    'Texas, Eastern': 'Eastern District of Texas',
    'Texas, Northern': 'Northern District of Texas',
    'Texas, Western': 'Western District of Texas',
    'Utah, Utah': 'District of Utah',
    'Vermont, Vermont': 'District of Vermont',
    'Virginia, Western': 'Western District of Virginia',
    'Virginia, Eastern': 'Eastern District of Virginia',
    'Washington, Western': 'Western District of Washington',
    'Washington, Eastern': 'Eastern District of Washington',
    'West Virginia, Northern': 'Northern District of West Virginia',
    'West Virginia, Southern': 'Southern District of West Virginia',
    'Wisconsin, Western': 'Western District of Wisconsin',
    'Wisconsin, Eastern': 'Eastern District of Wisconsin',
    'Wyoming, Wyoming': 'District of Wyoming'
}

JUDGE_DIST_MAP = district_name_map = {
    "U.S. District Court for the District of Nevada": "District of Nevada",
    "U.S. District Court for the Northern District of Florida": "Northern District of Florida",
    "U.S. District Court for the District of Hawaii": "District of Hawaii",
    "U.S. District Court for the Western District of Missouri": "Western District of Missouri",
    "U.S. District Court for the Western District of Arkansas": "Western District of Arkansas",
    "U.S. District Court for the Western District of Pennsylvania": "Western District of Pennsylvania",
    "U.S. District Court for the Southern District of California": "Southern District of California",
    "U.S. District Court for the Northern District of California": "Northern District of California",
    "U.S. District Court for the Southern District of Illinois": "Southern District of Illinois",
    "U.S. District Court for the Northern District of Illinois": "Northern District of Illinois",
    "U.S. District Court for the Eastern District of Arkansas": "Eastern District of Arkansas",
    None: None,
    "U.S. District Court for the Eastern District of Texas": "Eastern District of Texas",
    "U.S. District Court for the District of Maryland": "District of Maryland",
    "U.S. District Court for the District of New Hampshire": "District of New Hampshire",
    "U.S. District Court for the Western District of Texas": "Western District of Texas",
    "U.S. District Court for the Western District of Kentucky": "Western District of Kentucky",
    "U.S. District Court for the District of Alaska": "District of Alaska",
    "U.S. District Court for the Southern District of Ohio": "Southern District of Ohio",
    "U.S. District Court for the Middle District of Georgia": "Middle District of Georgia",
    "U.S. District Court for the District of Minnesota": "District of Minnesota",
    "U.S. District Court for the Western District of New York": "Western District of New York",
    "U.S. District Court for the Northern District of Iowa": "Northern District of Iowa",
    "U.S. District Court for the Eastern District of California": "Eastern District of California",
    "U.S. District Court for the Middle District of Tennessee": "Middle District of Tennessee",
    "U.S. District Court for the Eastern District of Oklahoma": "Eastern District of Oklahoma",
    "U.S. District Court for the Eastern District of Washington": "Eastern District of Washington",
    "U.S. District Court for the Eastern District of Louisiana": "Eastern District of Louisiana",
    "U.S. District Court for the Middle District of Alabama": "Middle District of Alabama",
    "U.S. District Court for the Eastern District of Michigan": "Eastern District of Michigan",
    "U.S. District Court for the District of North Dakota": "District of North Dakota",
    "U.S. District Court for the District of Massachusetts": "District of Massachusetts",
    "U.S. District Court for the Northern District of Oklahoma": "Northern District of Oklahoma",
    "U.S. District Court for the Eastern District of Missouri": "Eastern District of Missouri",
    "U.S. District Court for the District of Idaho": "District of Idaho",
    "U.S. District Court for the Eastern District of New York": "Eastern District of New York",
    "U.S. District Court for the Western District of Michigan": "Western District of Michigan",
    "U.S. District Court for the District of Utah": "District of Utah",
    "U.S. District Court for the Western District of Virginia": "Western District of Virginia",
    "U.S. District Court for the District of Wyoming": "District of Wyoming",
    "U.S. District Court for the Northern District of Ohio": "Northern District of Ohio",
    "U.S. District Court for the District of South Carolina": "District of South Carolina",
    "U.S. District Court for the District of New Jersey": "District of New Jersey",
    "U.S. District Court for the Northern District of New York": "Northern District of New York",
    "U.S. District Court for the District of Rhode Island": "District of Rhode Island",
    "U.S. District Court for the Western District of Tennessee": "Western District of Tennessee",
    "U.S. District Court for the Western District of North Carolina": "Western District of North Carolina",
    "U.S. District Court for the Western District of Wisconsin": "Western District of Wisconsin",
    "U.S. District Court for the Southern District of Florida": "Southern District of Florida",
    "U.S. District Court for the Northern District of Texas": "Northern District of Texas",
    "U.S. District Court for the District of Maine": "District of Maine",
    "U.S. District Court for the Northern District of Alabama": "Northern District of Alabama",
    "U.S. District Court for the Eastern District of Tennessee": "Eastern District of Tennessee",
    "U.S. District Court for the District of Delaware": "District of Delaware",
    "U.S. District Court for the Southern District of Alabama": "Southern District of Alabama",
    "U.S. District Court for the Middle District of North Carolina": "Middle District of North Carolina",
    "U.S. District Court for the Southern District of New York": "Southern District of New York",
    "U.S. District Court for the District of Puerto Rico": "District of Puerto Rico",
    "U.S. District Court for the District of Arizona": "District of Arizona",
    "U.S. District Court for the Central District of Illinois": "Central District of Illinois",
    "U.S. District Court for the District of New Mexico": "District of New Mexico",
    "U.S. District Court for the Western District of Washington": "Western District of Washington",
    "U.S. District Court for the Southern District of Iowa": "Southern District of Iowa",
    "U.S. District Court for the District of Connecticut": "District of Connecticut",
    "U.S. District Court for the Middle District of Florida": "Middle District of Florida",
    "U.S. District Court for the District of Columbia": "District of District of Columbia",
    "U.S. District Court for the Eastern District of Kentucky": "Eastern District of Kentucky",
    "U.S. District Court for the Southern District of Indiana": "Southern District of Indiana",
    "U.S. District Court for the Eastern District of Pennsylvania": "Eastern District of Pennsylvania",
    "U.S. District Court for the Eastern District of Virginia": "Eastern District of Virginia",
    "U.S. District Court for the District of South Dakota": "District of South Dakota",
    "U.S. District Court for the Northern District of Indiana": "Northern District of Indiana",
    "U.S. District Court for the Central District of California": "Central District of California",
    "U.S. District Court for the Eastern District of Wisconsin": "Eastern District of Wisconsin",
    "U.S. District Court for the Western District of Oklahoma": "Western District of Oklahoma",
    "U.S. District Court for the Middle District of Louisiana": "Middle District of Louisiana",
    "U.S. District Court for the Western District of Louisiana": "Western District of Louisiana",
    "U.S. District Court for the District of Kansas": "District of Kansas",
    "U.S. District Court for the District of Vermont": "District of Vermont",
    "U.S. District Court for the Southern District of West Virginia": "Southern District of West Virginia",
    "U.S. District Court for the Eastern District of North Carolina": "Eastern District of North Carolina",
    "U.S. District Court for the Southern District of Mississippi": "Southern District of Mississippi",
    "U.S. District Court for the Northern District of Georgia": "Northern District of Georgia",
    "U.S. District Court for the District of Colorado": "District of Colorado",
    "U.S. District Court for the Southern District of Texas": "Southern District of Texas",
    "U.S. District Court for the Southern District of Georgia": "Southern District of Georgia",
    "U.S. District Court for the District of Oregon": "District of Oregon",
    "U.S. District Court for the Northern District of West Virginia": "Northern District of West Virginia",
    "U.S. District Court for the District of Nebraska": "District of Nebraska",
    "U.S. District Court for the Northern District of Mississippi": "Northern District of Mississippi",
    "U.S. District Court for the Middle District of Pennsylvania": "Middle District of Pennsylvania",
    "U.S. District Court for the District of Montana": "District of Montana",
}


USSC_MAP = {
  "code_mappings": {

    "AGE": {},  
    "ACCAP": {},  
    "ACCTRESP": {},
    "BOOKERCD": {
      "0": "Within Range",
      "1": "Upward Departure",
      "2": "Upward Departure w/Booker",
      "3": "Above Range w/Booker",
      "4": "Remaining Above Range",
      "5": "5K1.1/Substantial Assistance",
      "6": "Early Disposition/5K3.1",
      "7": "Government Sponsored - Below Range",
      "8": "Downward Departure",
      "9": "Downward Departure w/Booker",
      "10": "Below Range w/Booker",
      "11": "Remaining Below Range"
    },
    "COADJLEV" : {},
    "CRIMHIST": {},
    "CAROFFAP" : {}, 
    "CIRCDIST": {
      "1": "District of District of Columbia",
      "2": "District of Maine",
      "3": "District of Massachusetts",
      "4": "District of New Hampshire",
      "5": "District of Puerto Rico",
      "6": "District of Rhode Island",
      "7": "District of Connecticut",
      "8": "Eastern District of New York",
      "9": "Northern District of New York",
      "10": "Southern District of New York",
      "11": "Western District of New York",
      "12": "District of Vermont",
      "13": "District of Delaware",
      "14": "District of New Jersey",
      "15": "Eastern District of Pennsylvania",
      "16": "Middle District of Pennsylvania",
      "17": "Western District of Pennsylvania",
      "18": "District of US Virgin Islands",
      "19": "District of Maryland",
      "20": "Eastern District of North Carolina",
      "21": "Middle District of North Carolina",
      "22": "Western District of North Carolina",
      "23": "District of South Carolina",
      "24": "Eastern District of Virginia",
      "25": "Western District of Virginia",
      "26": "Northern District of West Virginia",
      "27": "Southern District of West Virginia",
      "28": "Eastern District of Louisiana",
      "29": "Middle District of Louisiana",
      "30": "Western District of Louisiana",
      "31": "Northern District of Mississippi",
      "32": "Southern District of Mississippi",
      "33": "Eastern District of Texas",
      "34": "Northern District of Texas",
      "35": "Southern District of Texas",
      "36": "Western District of Texas",
      "37": "Eastern District of Kentucky",
      "38": "Western District of Kentucky",
      "39": "Eastern District of Michigan",
      "40": "Western District of Michigan",
      "41": "Northern District of Ohio",
      "42": "Southern District of Ohio",
      "43": "Eastern District of Tennessee",
      "44": "Middle District of Tennessee",
      "45": "Western District of Tennessee",
      "46": "Central District of Illinois",
      "47": "Northern District of Illinois",
      "48": "Southern District of Illinois",
      "49": "Northern District of Indiana",
      "50": "Southern District of Indiana",
      "51": "Eastern District of Wisconsin",
      "52": "Western District of Wisconsin",
      "53": "Eastern District of Arkansas",
      "54": "Western District of Arkansas",
      "55": "Northern District of Iowa",
      "56": "Southern District of Iowa",
      "57": "District of Minnesota",
      "58": "Eastern District of Missouri",
      "59": "Western District of Missouri",
      "60": "District of Nebraska",
      "61": "District of North Dakota",
      "62": "District of South Dakota",
      "63": "District of Alaska",
      "64": "District of Arizona",
      "65": "Central District of California",
      "66": "Eastern District of California",
      "67": "Northern District of California",
      "68": "Southern District of California",
      "69": "District of Guam",
      "70": "District of Hawaii",
      "71": "District of Idaho",
      "72": "District of Montana",
      "73": "District of Nevada",
      "74": "District of Northern Marianas Islands",
      "75": "District of Oregon",
      "76": "Eastern District of Washington",
      "77": "Western District of Washington",
      "78": "District of Colorado",
      "79": "District of Kansas",
      "80": "District of New Mexico",
      "81": "Eastern District of Oklahoma",
      "82": "Northern District of Oklahoma",
      "83": "Western District of Oklahoma",
      "84": "District of Utah",
      "85": "District of Wyoming",
      "86": "Middle District of Alabama",
      "87": "Northern District of Alabama",
      "88": "Southern District of Alabama",
      "89": "Middle District of Florida",
      "90": "Northern District of Florida",
      "91": "Southern District of Florida",
      "92": "Middle District of Georgia",
      "93": "Northern District of Georgia",
      "94": "Southern District of Georgia"
    },
    "CITIZEN": {
      "1": "U.S. Citizen",
      "2": "Resident",
      "3": "Illegal",
      "4": "Not a U.S. Citizen/Alien Status Unknown",
      "5": "Extradited Alien"
    },
    "CITWHERE": {
      "20": "CUB",
      "21": "ARG",
      "22": "BHS",
      "23": "BLZ",
      "24": "BOL",
      "25": "CAN",
      "26": "CHL",
      "27": "CHN",
      "28": "COL",
      "29": None,
      "30": "DOM",
      "31": "ECU",
      "32": "SLV",
      "33": "FRA",
      "34": "DEU",
      "35": "GHA",
      "36": "GBR",
      "37": "GTM",
      "38": "GUY",
      "39": "HTI",
      "40": "HND",
      "41": "IND",
      "42": "IRN",
      "43": "ISR",
      "44": "ITA",
      "45": "JAM",
      "46": "JOR",
      "47": "KOR",
      "48": "LBN",
      "49": "MEX",
      "50": "NIC",
      "51": "NGA",
      "52": "PAK",
      "53": "PAN",
      "54": "PER",
      "55": "PHL",
      "56": "RUS",
      "57": "THA",
      "58": "TTO",
      "59": "VEN",
      "60": "VNM",
      "61": "AFG",
      "62": "ALB",
      "63": "ATG",
      "64": "AUS",
      "65": "BGD",
      "66": "BRB",
      "67": "BEN",
      "68": "BRA",
      "69": "CRI",
      "70": "GRC",
      "71": "GIN",
      "72": "HKG",
      "73": "IDN",
      "74": "IRQ",
      "75": "IRL",
      "76": "KWT",
      "77": None,
      "78": "LAO",
      "79": "LBR",
      "80": "MYS",
      "81": "NLD",
      "82": "POL",
      "83": "ROU",
      "84": "PRT",
      "85": "ESP",
      "87": "SYR",
      "88": "TWN",
      "89": "TGO",
      "90": "YEM",
      "91": "YUG", 
      "98": None,
      "99": None,
      "100": "DZA",
      "101": "AND",
      "102": "AGO",
      "103": "ARM",
      "104": "AUT",
      "105": "AZE",
      "106": "BHR",
      "107": "BLR",
      "108": "BEL",
      "109": "BTN",
      "110": "BIH",
      "111": "BWA",
      "112": "BRN",
      "113": "BGR",
      "114": "BFA",
      "115": "BDI",
      "116": "KHM",
      "117": "CMR",
      "118": "CPV",
      "119": "CAF",
      "120": "TCD",
      "121": "COM",
      "122": "COG",
      "123": "CIV",
      "124": "HRV",
      "125": "CYP",
      "126": "CZE",
      "127": "DNK",
      "128": "DJI",
      "129": "DMA",
      "130": "EGY",
      "131": "ERI",
      "132": "EST",
      "133": "ETH",
      "134": "FJI",
      "135": "FIN",
      "136": "GAB",
      "137": "GMB",
      "138": "GEO",
      "139": "GRD",
      "140": "HUN",
      "141": "ISL",
      "142": "JPN",
      "143": "KAZ",
      "144": "KEN",
      "145": "KGZ",
      "146": "LVA",
      "147": "LSO",
      "148": "LBY",
      "149": "LIE",
      "150": "LTU",
      "151": "LUX",
      "152": "MDG",
      "153": "MWI",
      "154": "MDV",
      "155": "MLI",
      "156": "MLT",
      "157": "MHL",
      "158": "MRT",
      "159": "MUS",
      "160": "FSM",
      "161": "MDA",
      "162": "MCO",
      "163": "MNG",
      "164": "MAR",
      "165": "MOZ",
      "166": "MMR",
      "167": "NAM",
      "168": "NPL",
      "169": "NZL",
      "170": "NOR",
      "171": "OMN",
      "172": "PLW",
      "173": "PNG",
      "174": "PRY",
      "175": "QAT",
      "176": "RWA",
      "177": "LCA",
      "178": "VCT",
      "179": "WSM",
      "180": "SMR",
      "181": "STP",
      "182": "SAU",
      "183": "SEN",
      "184": "SYC",
      "185": "SLE",
      "186": "SGP",
      "187": "SVK",
      "188": "SVN",
      "189": "SLB",
      "190": "SOM",
      "191": "ZAF",
      "192": "LKA",
      "193": "SDN",
      "194": "SUR",
      "195": "SWZ",
      "196": "SWE",
      "197": "CHE",
      "198": "TJK",
      "199": "TZA",
      "200": "TUN",
      "201": "TUR",
      "202": "TKM",
      "203": "UGA",
      "204": "UKR",
      "205": "ARE",
      "206": "URY",
      "207": "UZB",
      "208": "VUT",
      "209": "ZMB",
      "210": "ZWE",
      "211": "USA",
      "212": "BMU",
      "213": "MSR",
      "214": "MKD",
      "215": "KNA",
      "216": "TON",
      "217": "NER",
      "218": "KIR",
      "219": "MNE",
      "220": "SRB",
      "221": "XKX",
      "222": "PSE"
    },
    "DSIND" : {
      "0": "Not Received",
      "1": "Received Complete",
      "3": "Received Partial or Alternate Doc"
    },
    "DSJANDC": {
      "0": "Not Received",
      "1": "Complete",
      "3": "Partial or Alternate Doc"
    },
    "DSPLEA" : {
      "0": "Not Received",
      "1": "Received",
      "2": "Received Alternate Document",
      "3": "Oral Plea Agreement",
      "5": "Straight up Plea, No Agreement",
      "8": "Trial",
      "9": "Guilty Plea, Type Indeterminable"
    },
    "DSPSR": {
      "0": "Not Received",
      "1": "Received Complete",
      "2": "Received Partial/Alternate Doc",
      "8": "Waived"
    },
    "DSSOR": {
      "0": "Not Received",
      "1": "Received Complete",
      "2": "Received Partial/Alternate Doc",
      "3": "Received Blank",
      "8": "Will Never Be Received"
    },
    "EDUCATN": {
      "0": "Less than High School",
      "1": "Less than High School",
      "2": "Less than High School",
      "3": "Less than High School",
      "4": "Less than High School",
      "5": "Less than High School",
      "6": "Less than High School",
      "7": "Less than High School",
      "8": "Less than High School",
      "9": "Less than High School",
      "10": "Less than High School",
      "11": "Less than High School",
      "37": "Less than High School",
      "31": "Less than High School",
      "32": "Less than High School",

      "12": "High School",
      "21": "High School",

      "13": "Some College",
      "14": "Some College",
      "15": "Some College",
      "33": "Some College",
      "34": "Some College",
      "22": "Some College",
      "23": "Some College",
      "36": "Some College",

      "16": "Bachelor's Degree",

      "24": "Graduate Degree",
      "35": "Graduate Degree"
    },
    "FSASV":{
      "0": "No First Step Act Safety Valve indicated",
      "1": "First Step Act Safety Valve indicated"
    },
    "GLMAX":{
      "9996": "Life"
    },
    "GLMIN":{
      "9996": "Life"
    },
    "INNOPL":{
      "1": "5K1.1 motion",
      "2": "Govt. motion for a departure",
      "3": "Defense motion which govt has NOT objected",
      "4": "Defense motion which the govt HAS objected",
      "5": "Other than a plea agreement or a motion by the parties",
      "6": "§5K3.1 Early Disposition Program",
      "7": "Joint motion by both parties"
    },
    # we flip the meaning of the INOUT variable so that 1 = in and 0 = out, which is more intuitive for our purposes
    "INOUT":{
        "1": "0",
        "0": "1"
    }, 
    "INPLEA": {
      "1": "5K1.1 motion",
      "2": "5K3.1 EDP/Fast Track program",
      "3": "BINDING Plea Agreement",
      "4": "Plea Agreement which cites reason for departure which court finds to be justified",
      "5": "Plea Agreement which states govt will NOT oppose defense motion for departure"
    },
    "MOCOMCON":{
      "97": "Unspecified Term"
    },
    "MOHOMDET":{
      "97": "Unspecified Term"
    },
    "MOINTCON":{
      "97": "Unspecified Term" 
    },
    "MONSEX":{  
      "0": "Male",
      "1": "Female",
      "2": "Other"
    },
    "NEWCNVTN":{},  
    "NEWRACE":{  
      "1": "White",
      "2": "Black",
      "3": "Hispanic",
      "6": "Other"
    },
    "NOCOUNTS":{},  
    "NUMDEPEN":{
      "97": "Unspecified No. of Dependents" 
    },
    "OBST":{},
    "OFFGUIDE":{
      "1": "Administration of Justice",
      "2": "Antitrust",
      "3": "Arson",
      "4": "Assault",
      "5": "Bribery/Corruption",
      "6": "Burglary/Trespass",
      "7": "Child Pornography",
      "8": "Commercialized Vice",
      "9": "Drug Possession",
      "10": "Drug Trafficking",
      "11": "Environmental",
      "12": "Extortion/Racketeering",
      "13": "Firearms",
      "14": "Food and Drug",
      "15": "Forgery/Counter/Copyright",
      "16": "Fraud/Theft/Embezzlement",
      "17": "Immigration",
      "18": "Individual Rights",
      "19": "Kidnapping",
      "20": "Manslaughter",
      "21": "Money Laundering",
      "22": "Murder",
      "23": "National Defense",
      "24": "Obscenity/Other Sex Offenses",
      "25": "Prison Offenses",
      "26": "Robbery",
      "27": "Sex Abuse",
      "28": "Stalking/Harassing",
      "29": "Tax",
      "30": "Other"
    },
    "OFFTYPSB":{
      "1": "Murder",
      "2": "Manslaughter",
      "3": "Kidnapping/Hostage Taking",
      "4": "Sexual Abuse",
      "5": "Assault",
      "6": "Robbery",
      "9": "Arson",
      "10": "Drugs - Trafficking, Manufacturing, and Importing",
      "11": "Drugs - Communication Facilities",
      "12": "Drugs: - Simple Possession",
      "13": "Firearms (Includes Firearms Use, Possession, and Trafficking)",
      "15": "Burglary/Breaking and Entering",
      "16": "Auto Theft",
      "17": "Larceny",
      "18": "Fraud",
      "19": "Embezzlement",
      "20": "Forgery/Counterfeiting",
      "21": "Bribery",
      "22": "Tax Offenses",
      "23": "Money Laundering",
      "24": "Racketeering /Extortion",
      "25": "Gambling/Lottery",
      "26": "Civil Rights Offenses",
      "27": "Immigration",
      "28": "Child Pornography (includes OFFTYPE2=42, Child Pornography)",
      "29": "Prison Offenses",
      "30": "Administration of Justice (Includes accessory after the fact, misprision of felony, and witness tampering)",
      "31": "Environmental, Game, Fish, and Wildlife Offenses",
      "32": "National Defense Offenses",
      "33": "Antitrust Violations",
      "34": "Food and Drug Offenses",
      "35": "Traffic Violations and Other Offenses (Includes Other Drug, Environmental, Firearms, Miscellaneous Property Crimes, Violent, Traffic offenses, Obscenity, and Prostitution) (Includes OFFTYPE2= 43,44)"
    },
    "OFFV":{},
    "PRESENT":{
      "1": "In Custody",
      "2": "Bail/Bond",
      "3": "Released on Own Recognizance",
      "4": "Other"
    },
    "PRISDUM":{}, 
    "PROBATN":{
      "997": "Unspecified Term"
    },
    "REAS":{
      "0": "No reason given",
      "1": "Nature and circs of offense and history and char. of def (18 3553(a)(1))",
      "2": "Reflect seriousness of offense, promote respect for law, provide just punishment for the offense (18 3553(a)(2)(A))",
      "3": "Afford adequate deterrence to criminal conduct (18 3553(a)(2)(B))",
      "4": "Protect the public from further crimes of the defendant (18 3553(a)(2)(C))",
      "5": "Provide the def with needed educational or vocational training, medical care or other correctional treatment in most effective manner (18 3553(a)(2)(D))",
      "6": "Avoid unwarranted sentencing disparities among defendants",
      "7": "Provide Restitution to any victims of the offense",
      "10": "(5G1.3) Convictions on related counts",
      "11": "(5H1.1) Age (Defendant’s youth or old age)",
      "12": "(5H1.2) Educational and vocational skills",
      "13": "(5H1.3) Mental and emotional conditions",
      "14": "(5H1.4) Physical condition",
      "15": "(5H1.4) Drug dependence and alcohol abuse",
      "16": "(5H1.5) Previous employment record",
      "17": "(5H1.6) Family ties and responsibilities",
      "18": "(5H1.6) Community ties",
      "19": "(5K1.1) Substantial assistance WITH govt. motion",
      "20": "(not 5K1.1) Cooperation without motion",
      "21": "Cooperation (motion unknown)",
      "22": "Several persons injured",
      "23": "(5K2.1) Death",
      "24": "(5K2.2) Physical injury",
      "25": "(5K2.3) Extreme psychological injury",
      "26": "(5K2.4) Abduction or unlawful restraint",
      "27": "(5K2.5) Property damage or loss",
      "28": "(5K2.6) Weapons and dangerous instrumentalities",
      "29": "(5K2.7) Disruption of governmental function",
      "30": "(5K2.8) Extreme conduct",
      "31": "(5K2.9) Criminal purpose",
      "32": "(5K2.10) Victim's conduct",
      "33": "(5K2.11) Lesser harm",
      "34": "(5K2.12) Coercion and duress",
      "35": "(5K2.13) Diminished capacity",
      "36": "(5K2.14) Public welfare",
      "37": "Fast Track",
      "38": "Totality of Circumstances/Combination of Factors (Cook/Koon)",
      "39": "Circumstances not Considered by the Guidelines",
      "40": "EDP Disparity",
      "41": "(4A1.3) Criminal History Adequacy Explain",
      "42": "(5K2.17) High-Capacity Semiautomatic Firearm",
      "43": "(5K2.18) Violent Street Gang",
      "44": "(5K2.20) Aberrant Behavior",
      "45": "(5K2.21) Dismissed and Uncharged Conduct",
      "46": "(5K2.22) Age or Health of Sex Offenders",
      "47": "(5K2.23) Discharge Terms of Imprisonment",
      "48": "(5K3.1) Early Disposition. Fast Track program",
      "49": "(5K2.24) Commit offense while wearing/displaying unauth/counterfeit uniform",
      "51": "Charge Bargaining",
      "52": "Unspecified government motion (Not 5K1.1 or 5K3.1)",
      "53": "Defendant Unaware of Type/Quantity/Purity of Drugs",
      "54": "Mitigating Factors Regarding Illegal Entry",
      "55": "Victim of Abuse (Not Childhood Abuse)",
      "56": "(2D2.1) Application note 1 (Intended Consumption by Person Other than def)",
      "57": "No Benefit of Incarceration to Def",
      "58": "Charitable Service/Good Works",
      "59": "Mens Rea",
      "60": "The nature and circumstance of the offense pursuant to 18 U.S.C. 3553(a)(1)",
      "61": "The history and characteristics of the defendant pursuant to 18 U.S.C. 3553(a)(1)",
      "62": "To provide the defendant with needed educational or vocational training (18 U.S.C. 3553(a)(2)(D))",
      "63": "To provide the defendant with medical care (18 U.S.C. 3553(a)(2)(D))",
      "64": "To provide the defendant with other correctional treatment in the most effective manner (18 U.S.C. 3553(a)(2)(D))",
      "65": "Policy Disagreement with the Guidelines (Kimbrough v. U.S. 552 U.S. 85 (2007)",
      "66": "Victim Impact",
      "67": "Pre-Sentence Rehabilitation",
      "100": "(2A1.1) Death not caused intentionally",
      "101": "(2A2.1, 2A2.2) Degree of injury falls between two categories",
      "103": "(2A3.2) Criminal sexual act for commercial purpose",
      "105": "(2A6.1) Factors not incorporated in guideline",
      "106": "(2B1.3) Monetary value does not reflect extent of harm",
      "108": "(2B3.1) Intended to murder the victim",
      "110": "(2C1.1) Systematic or pervasive corruption of governmental function",
      "111": "(2D1.1) Drug Purity/Potency",
      "112": "(2D1.1) Unusually high drug amount",
      "113": "Drug Quantity",
      "114": "(2D1.5) Sanctioned use of violence in enterprise",
      "115": "Crack/Powder Disparity",
      "118": "(2F1.1) Loss substantially exceeds maximum from loss table",
      "119": "(2F1.1) Dollar loss overstates seriousness of offense",
      "120": "(2F1.1) Fraudulent statements could be covered by more specific statute",
      "121": "(2G1.1) Offense did not involve profit nor physical force or coercion",
      "124": "2H2.1 Corrupting a public official /bodily injury /property damage",
      "125": "(2L1.1) Large number of aliens",
      "126": "(2L1.1) Dangerous or inhumane treatment",
      "127": "(2L2.2, 2L2.4) Deported on one or more prior occasions",
      "128": "(2M3.1, 2M3.7, 2M3.9) Revelation causes little or no harm",
      "131": "(2M5.1, 2M5.2) Extreme threat to national security",
      "132": "(2M5.1, 2M5.2) Extreme volume of commerce involved",
      "134": "(2M5.1, 2M5.2) Extreme number of multiple occurrences",
      "137": "(2N2.1,2Q1.2) Negligence involved",
      "139": "(2Q1.2, 2Q1.3) Harm resulting from emission, release or discharge",
      "140": "(2Q1.2, 2Q1.3) Harm resulting from quantity & nature of substance or pollutant",
      "141": "(2Q1.2, 2Q1.3) Harm resulting from duration of offense",
      "142": "(2Q1.2, 2Q1.3) Harm resulting from risk",
      "143": "(2Q1.2, 2Q1.3) Nature of risk",
      "144": "(2Q1.2, 2Q1.3) Number of people at risk",
      "145": "(2Q1.2, 2Q1.3) Nature of contamination",
      "146": "(2Q1.2, 2Q1.3) Similar conduct by civil adjudication",
      "147": "(2Q1.2, 2Q1.3) Failure to comply with administrative order",
      "148": "(2T1.6) Tax evasion and embezzlement",
      "151": "(2T3.1,2) Import. of drugs, obscene matter, firearms, pelts of endangered species",
      "152": "(2T3.1) Duties may not adequately reflect harm",
      "200": "(3A1.2) Exceptionally high level victim",
      "201": "(3C1.1) Further obstruction of justice",
      "202": "5C1.2 (Safety Valve)",
      "203": "Obstruction without 3C1.1",
      "204": "Unsophisticated Nature of Offense",
      "205": "Defendant’s Support Network (unspecified)",
      "206": "Def will serve additional time on a revocation/state conviction",
      "207": "Defendant was assaulted in custody",
      "208": "Defendant has made/prepared for a new life in another country",
      "209": "Motive for Instant Offense (Not 2L1.2 Offenses)",
      "210": "Conduct in Court",
      "211": "Defendant’s Maturity/Immaturity",
      "212": "Instant offense unlike other offenses of the same type",
      "213": "Defendant absconded/evaded/fled arrest",
      "214": "False Statements to LEO/PO/etc.",
      "215": "Reckless Behavior",
      "216": "High Likelihood of Recidivism/Defendant IS a threat to the public",
      "217": "Potential for future rehabilitation",
      "250": "(3D1.4) Offenses significantly more than 5 units",
      "300": "(4A1.3) Pattern of conduct",
      "301": "(4A1.3) Pending cases",
      "302": "(4A1.3) Related cases",
      "304": "Gen. adequacy of crim. history; does not reflect seriousness of crim. hist",
      "305": "(4A1.3) Outside applicable time period, but similar misconduct",
      "306": "(4A1.3) Outside applicable time period, but substantial portion of income",
      "307": "(4A1.3) Significance or similarity of past conduct",
      "308": "Other adequacy of criminal history",
      "309": "Criminal history category over-represents the defendant's involvement",
      "310": "Prior criminal record; risk of future criminal conduct",
      "311": "Age of Priors",
      "312": "First Federal Conviction",
      "313": "Little/No Incarceration for Priors",
      "314": "Age when prior was committed",
      "315": "Criminal History (largely) due to drug addiction",
      "316": "Marijuana priors in criminal history",
      "400": "Unconvicted behavior added under relevant conduct",
      "401": "(4B1.3) Criminal livelihood",
      "402": "(4B1.1) Career offender",
      "500": "Pursuant to a NONbinding (or unknown type) plea agreement",
      "501": "Due to stipulations",
      "502": "Other plea agreement reasons",
      "503": "Pursuant to a binding plea agree 11(c)(1)(C)",
      "504": "Statmin/Max",
      "648": "Alien Status",
      "649": "Cultural Assimilation",
      "650": "Mule/Role in the offense",
      "651": "Interpolation",
      "652": "Deportation",
      "653": "Local conditions",
      "654": "Adequate punishment to meet the purposes of sentencing",
      "655": "Deterrence",
      "656": "Prey to other inmates / Susceptibility to abuse in prison",
      "657": "Reduce disparity",
      "658": "Charge/Plea does not reflect the seriousness of the offense",
      "659": "Guidelines do not reflect the seriousness of the offense",
      "660": "Justifiable Reasons",
      "661": "No prior record/first offense",
      "662": "Put sentence in line with codefendant's. (i.e. Reduce disparity among codefendants)",
      "663": "High speed chase",
      "664": "Lack of culpability/accountability of defendant",
      "665": "Lost job/punishment enough",
      "666": "Lack of available facilities/overcrowding",
      "667": "Non-Guideline Sentence",
      "668": "Nonviolent Offense",
      "669": "Indigent background",
      "670": "Impact on Employment of Self/Others",
      "671": "Time or cost involved in the investigation",
      "672": "Defendant's propensity for violence",
      "673": "Acceptance of responsibility",
      "674": "Limited/Minor prior record",
      "675": "Training /Treatment Opportunities",
      "676": "Rehabilitation",
      "677": "Restitution",
      "678": "Incapacitation",
      "679": "Sufficient punishment",
      "680": "Nature/Seriousness of the offense",
      "681": "First felony conviction",
      "683": "On-going nature of activity",
      "684": "Terminated Offense Prior to Arrest/Discovery",
      "685": "Low Likelihood of Recidivism",
      "686": "Conduct on Release/Bond/Supervision",
      "687": "Limited/No Loss or Monetary Benefit",
      "688": "Dollar amount involved in crime (general)",
      "689": "Minors involved",
      "690": "Untruthful testimony",
      "691": "Terrifying the victim",
      "692": "Influenced/Used by Others",
      "693": "Cost of Incarceration",
      "695": "Currently receiving punishment under state or federal jurisdiction",
      "696": "Mitigating Factors regarding Firearms",
      "697": "Defendant's positive background/good character",
      "698": "Defendant's negative background/bad character",
      "700": "Not representative of the 'heartland'",
      "701": "Guidelines too high/offense level over-represented",
      "702": "Guidelines too low/offense level under-represented",
      "703": "(5K2.0) General aggravating or mitigating circumstance",
      "704": "(4A1.3) Seriousness of criminal history substantially underrepresented by CHC",
      "705": "(4A1.3) Likelihood of recidivism underrepresented by Crim Hist Cat",
      "706": "(2C1.1) Payment not reflect seriousness of offense",
      "707": "(2L1.1) Knowingly smuggled alien who intended to engage in serious crim. activity",
      "708": "(2B1.1) Offense level understate offense seriousness",
      "709": "(2B1.1) Offense Level overstates offense seriousness",
      "710": "(2B1.1) Offense level disrupts critical infrastructure",
      "711": "(5G1.3)",
      "712": "Advisory nature of guidelines",
      "713": "Judge specifies presence of variance / deviation",
      "719": "Cooperation/Attempted Cooperation (not 5K, not with prosecution, per se)",
      "720": "5K1.1 Subst. Assist. WITHOUT govt. motion",
      "721": "5H1.11 Military Record/Charitable Service/Good Works",
      "722": "Charitable Service/Good Works",
      "730": "Early Plea",
      "731": "Global Plea",
      "732": "Expeditious Resolution",
      "733": "Waiver of collateral attacks",
      "734": "Waiver of Motions",
      "740": "Savings to government",
      "741": "Waiver of appeal",
      "742": "Waiver of indictment",
      "743": "Global disposition",
      "744": "As stated on record",
      "745": "SOR references an exhibit (eg., \"See Exhibit C\")",
      "746": "See Transcript/Rider/PSR",
      "747": "Party Motion /Agreement /Consent (Reason Unspecified)",
      "750": "Reasonableness",
      "751": "Interest of Justice",
      "760": "US v Booker / US v Fanfan",
      "761": "18 USC 3553(a)",
      "762": "Language from 18 USC 3553(a) statute text",
      "763": "2007 New Crack Table Amendment",
      "777": "Other (SPECIFY)",
      "778": "Other (SPECIFY)",
      "779": "Other (SPECIFY)",
      "780": "Other (SPECIFY)",
      "781": "Other (SPECIFY)",
      "782": "Other (SPECIFY)",
      "783": "Other (SPECIFY)",
      "784": "Other (SPECIFY)",
      "785": "Other (SPECIFY)",
      "786": "Other (SPECIFY)",
      "787": "Other (SPECIFY)",
      "788": "Other (SPECIFY)",
      "789": "Other (SPECIFY)",
      "790": "Other (SPECIFY)",
      "791": "Other (SPECIFY)",
      "792": "Other (SPECIFY)",
      "793": "Other (SPECIFY)",
      "794": "Other (SPECIFY)",
      "795": "Other (SPECIFY)",
      "796": "Other (SPECIFY)",
      "797": "Other (SPECIFY)",
      "798": "Other (SPECIFY)",
      "799": "Other (SPECIFY)",
      "801": "8C4.2, risk of death or bodily injury",
      "822": "Defendant is a law enforcement officer or ex-law enforcement officer",
      "823": "Offense behavior was an isolated incident",
      "824": "A lower sent. gives defend. a chance to become a productive member of society",
      "825": "(5K2.16) Voluntary Disclosure",
      "826": "Lack of Youthful Guidance",
      "827": "Delay in prosecution; evidentiary concerns",
      "828": "Time Served",
      "830": "Child abuse/ childhood abuse/ battered child syndrome",
      "831": "Remorse",
      "832": "Abuse of trust/skill/position",
      "833": "2L1.2 - Criminal History Issues",
      "834": "Limited Duration of Involvement",
      "835": "Conditions of Confinement",
      "836": "Kimbrough/Gall Supreme Court Decision",
      "837": "Good Time",
      "838": "Number of Images",
      "839": "No Inappropriate Conduct with Children/Not a Pedophile",
      "840": "Defendant did not Distribute Child Pornography",
      "841": "Rule 35b",
      "842": "Due to Spears Supreme Court Decision",
      "843": "Has had inappropriate contact with or exploited minors",
      "844": "Age of Victim (Only Porn or Sex Offenses)",
      "845": "Def participated in psychosexual assessment",
      "846": "No/Minor/Limited History of Drug/Alcohol Abuse/Defendant is not an Addict",
      "847": "Crime motivated by financial distress",
      "848": "Victim request/letter from victim to judge/PO",
      "849": "Age of Instant Offense",
      "850": "First immigration offense",
      "851": "Number of documents",
      "853": "No History of Mental Health Issues",
      "854": "Lack of Family Support",
      "855": "Forfeiture",
      "856": "No victims/no harm",
      "857": "Letters of support - unspecified from whom",
      "858": "Proposed changes to the 2D1.1 drug quantity table",
      "859": "Loss of Border Crossing Card/Privilege or LPR Status",
      "860": "Increase Over Similar Prior’s Sentence",
      "861": "Collateral Consequences of Offense",
      "862": "Conduct in jail/prison/custody",
      "863": "No Deportation/Immigration History",
      "864": "Limited Deportation/Immigration History",
      "865": "Non-Crack Drug Table Disparity",
      "866": "Gambling Addiction",
      "867": "Traumatic/Recent Loss of Family Members",
      "868": "Applied proposed guideline amendment",
      "869": "No Criminal Conduct (while in the US) other than Illegal Entry",
      "870": "Length of Time Since Last Deportation/Removal",
      "871": "No Firearm/Weapons Involved in the Offense",
      "872": "Lack of Treatment in Prior Sentences/Prior to Instant Offense",
      "873": "Issue with Child Porn Use of a Computer SOC",
      "874": "Tribal Court Convictions",
      "875": "First Step Act Safety Valve",
      "876": "COVID-19/pandemic",
      "877": "Did not create child pornography",
      "1200": "Criminal History Issues (aggregated reason)",
      "1201": "Unusually High Drug Amount/Purity (aggregated reason)",
      "1202": "General Guideline Adequacy Issues (aggregated reason)",
      "1203": "Loss Issues (aggregated reason)",
      "1205": "Insufficient Documentation Provided on SOR to Determine Reason (aggregated reason)",
      "1206": "Reduce Disparity (aggregated reason)",
      "1207": "§5H1.11 - Military Record/Charitable Works/Good Deeds (aggregated reason)",
      "1208": "§5G1.3 (aggregated reason)",
      "1209": "Cooperation without motion (not §5K1.1) (aggregated reason)",
      "1210": "(§4A1.1e) Recency Amendment (aggregated reason)",
      "1211": "Mental and Emotional Conditions (aggregated reason)",
      "1212": "First immigration offense (aggregated reason)",
      "1213": "Charitable Service/Good Works (aggregated reason)"
    },
    "RETEXT":{},
    "SAFE":{
      "0": "Not Applied",
      "1": "Received & Given Reduction",
      "2": "Received statutory safety valve, no reduction"
    },
    "SAFETY":{},
    "SENTIMP":{
      "0": "Fine Only",
      "1": "Prison Only",
      "2": "Prison & Alternatives",
      "3": "Probation & Alternatives",
      "4": "Probation Only"
    },
    "SENTMON":{},
    "SENTPTS":{},
    "SENTRNGE":{
      "0": "Within Range",
      "1": "Upward Departure",
      "2": "5K1.1/Substantial Assistance",
      "3": "Early Disposition/5K3.1",
      "4": "Govt. Sponsored Departure",
      "5": "Downward Departure",
      "6": "Above Range Variance",
      "7": "Govt. Sponsored Variance",
      "8": "Below Range Variance"
    },
    "SENTYR":{},
    "SOURCES":{
      "1": "No Guideline Discrepancies",
      "3": "Incomplete Guideline Information",
      "6": "18 U.S.C. § 924(c) only",
      "7": "18 U.S.C. § 1028A only",
      "8": "No applicable guidelines",
      "5": "Guideline information gathered from PSR (No SOR Present)",
      "9": "Guideline information missing and PSR Waived/Missing"
    },
    "STATMIN":{
      "9996": "Life",
      "9997": "Death"
    },
    "STATMAX":{
      "9996": "Life",
      "9997": "Death"
    },
    "TOTCHPTS":{},
    "SENTTOT":{
      "470": "Life"
    },
    "TYPEMONY":{
      "1": "Not ordered",
      "2": "Only restitution",
      "3": "Only Fine/Cost of Supervision",
      "4": "Fine/Cost of Supervision & Restitution"
    },
    "TYPEOTHS":{
      "0": "Regular Sentence",
      "1": "Suspended Prison Term",
      "2": "Pay Cost of Prosecution",
      "3": "Denial of Federal Benefits",
      "77": "Other Unique Sentence"
    },
    "TYPEOTTX":{},
    "XCRHISSR":{},
    "XFOLSOR":{},
    "ZONE":{},
    "YEAR": {}
  },

  "column_names": {
    "AGE": "AGE",  # age (in years) of the offender at the time of sentencing
    "ACCAP": "ARMD_CAREER_CRIM_ST",  # whether the offender was considered an armed criminal career by the guidelines
    "ACCTRESP": "ACC_RESP_ADJ",  # whether the offender received an adjustment to offense level for acceptance of responsibility
    "BOOKERCD": "SENT_RANGE_2004_2017",
    "CAROFFAP": "CR_OFNDR_FLAG",  # whether the offender was a career offender according to the guidelines
    "CIRCDIST": "DIST_CRT",  # the federal district court in which the offender was sentenced
    "CITWHERE": "CTRY_OF_CTZNSHP",  # the country of citizenship of the offender (3 digit iso code)
    "CITIZEN": "CITIZEN",  # the citizenship status of the offender
    "COADJLEV": "OL_B4_ACC_RESP",  # the offense level prior to any adjustments for acceptance of responsibility
    "CRIMHIST": "ANY_CRIM_HIST_FLAG",  # whether the offender had any prior criminal history, regardless of if it was counted under the guidelines
    # -- COLUMNS CURRENRLY NOT IN THE DATASET --
    "DSIND": "DOC_ST_INDICTMENT", 
    "DSJANDC": "DOC_ST_JC",
    "DSPLEA": "DOC_ST_PLEA_AGMT",
    "DSPSR": "DOC_ST_PSR",
    "DSSOR": "DOC_ST_SOR",
    # -- END COLUMNS CURRENTLY NOT IN THE DATASET --
    "EDUCATN": "EDUCATION",  # the highest level of education attained by the offender at the time of sentencing
    "FSASV": "VAR_FSA_SFTY_VLV",
    "GLMAX": "GL_MAX",  # the maximum sentence length (in months) under the guidelines 
    "GLMIN": "GL_MIN",  # the minimum sentence length (in months) under the guidelines
    "INNOPL": "ORGN_DPTR_NOT_FROM_PLEA",
    "INOUT": "RCVD_PRIS_SENT_ELGB_PROBAT", 
    "INPLEA": "ORGN_DPTR_FROM_PLEA",
    "MOCOMCON": "MNTHS_COM_CONFMT",  # the number of months of confinement ordered by the court 
    "MOHOMDET": "MNTHS_HOME_DETENT",  # the number of months of home detention ordered by the court
    "MOINTCON": "MNTHS_INTMT_CONFMT", # the number of months of intermittent confinement ordered by the court
    "MONSEX": "SEX",  # the sex of the individual
    "NEWCNVTN": "TRIAL_FLAG",  # whether the offender was convicted at trial or through a plea agreement
    "NEWRACE": "RACE",  # the race of the offender
    "NOCOUNTS": "NUM_COUNTS",  # the number of counts of conviction for the offender
    "NUMDEPEN": "NUM_DEPENDENTS",  # the number of dependents the offender had at the time of sentencing
    "OBST": "OBSTR_JUS_ADJ",  # guideline adjustment to offense level for obstruction of justice
    "OFFGUIDE": "OFF_TYPE_2018_PRSNT",  # offense type (the mappings of offense types was changed after FY2017, so there are two separate columns for offense type for the two time periods)
    "OFFTYPSB": "OFF_TYPE_2010_2017",  # offense type
    "OFFV": "LAW_ENFMT_VCTM_ADJ",  # guideline adjustment to offense level for being a law enforcement victim
    "PRESENT": "DETENT_ST",  # the offender's status at the time of sentencing (in custody, on bail, released on own recognizance, or other)
    "PRISDUM": "RECIEVED_PRSN_FLAG",  # whether the offender received a prison sentence (sentences of home detention only or probation only would be classified as 0).
    "PROBATN": "MNTHS_PROBAT",  # the number of months of probation ordered by the court
    "REAS": "REAS_OUTSIDE_GDLN",  # the reason for a sentence outside the guideline range
    "RETEXT": "OTHR_REAS_OUTSIDE_GDLN",  # other reasons for a sentence outside the guideline range
    "SAFE": "SAFETY_REDUCTION_GLDN",  # guideline adjustment for safety valve reduction
    "SAFETY": "RCVD_SAFETY_VLV",  # whether the offender received a safety valve reduction
    "SENTIMP": "TYPE_OF_SENT",  # the type of sentence (prison only, probation only, etc.)
    "SENTMON": "SENT_MNTH",  # the month of sentencing
    "SENTPTS": "OFF_CMTD_UNDER_SUP",  # the offense committed under supervision
    "SENTYR": "SENT_YR",  # the year of sentencing
    "SENTRNGE": "SENT_RANGE_2018_PRSNT",  # the sentence range for the offender
    "SOURCES": "SOURCES",  # the source of the guideline information. When certain documents are missing (e.g., no SOR, no PSR, etc.) the USSC will look towards other documents to fill in the missing information. This column indicates which documents wether the USSC was able to successfully fill in the missing information from other documents.
    "STATMIN": "STAT_MIN",  # the minimum sentence length (in months) allowed under the statute of conviction
    "STATMAX": "STAT_MAX",  # the maximum sentence length (in months) allowed under the statute of conviction
    "TOTCHPTS": "TOT_CH_PTS",  # the total number of criminal history points for the offender. This value is binned in order to create the criminal history category (CHC).
    "SENTTOT": "MNTHS_PRSN_NO_ALT",
    "TYPEMONY": "FINANCIAL_PEN", 
    "TYPEOTHS": "OTH_SENT_TYPES", 
    "TYPEOTTX": "OTH_SENT_TYPES_TXT",
    "XCRHISSR": "CHC",
    "XFOLSOR": "OL", 
    "ZONE": "ZONE_OF_SENT",
    "YEAR": "FISCAL_YR"
  }
}

OFF_TYPE_2018_PRSNT_MAP = {
    "Drug Trafficking": "Drugs",
    "Drug Possession": "Drugs",

    "Immigration": "Immigration",

    "Murder": "Violent",
    "Manslaughter": "Violent",
    "Assault": "Violent",
    "Robbery": "Violent",
    "Kidnapping": "Violent",
    "Arson": "Violent",

    "Firearms": "Weapons",

    "Fraud/Theft/Embezzlement": "Financial",
    "Money Laundering": "Financial",
    "Tax": "Financial",
    "Antitrust": "Financial",
    "Bribery/Corruption": "Financial",
    "Forgery/Counter/Copyright": "Financial",

    "Sex Abuse": "Sex",
    "Child Pornography": "Sex",
    "Obscenity/Other Sex Offenses": "Sex",
    "Commercialized Vice": "Sex",
    "Stalking/Harassing": "Sex",

    "Administration of Justice": "Other",
    "Extortion/Racketeering": "Other",
    "Prison Offenses": "Other",
    "National Defense": "Other",
    "Environmental": "Other",
    "Food and Drug": "Other",
    "Individual Rights": "Other",
    "Burglary/Trespass": "Other",
    "Other": "Other",
    None: "Other"
}

OFF_TYPE_2010_2017_MAP = {
    'Drugs - Trafficking, Manufacturing, and Importing': 'Drugs',
    'Drugs: - Simple Possession': 'Drugs',
    'Drugs - Communication Facilities': 'Drugs',

    'Immigration': 'Immigration',

    'Murder': 'Violent',
    'Manslaughter': 'Violent',
    'Assault': 'Violent',
    'Robbery': 'Violent',
    'Kidnapping/Hostage Taking': 'Violent',
    'Arson': 'Violent',

    'Firearms (Includes Firearms Use, Possession, and Trafficking)': 'Weapons',

    'Fraud': 'Financial',
    'Embezzlement': 'Financial',
    'Larceny': 'Financial',
    'Forgery/Counterfeiting': 'Financial',
    'Money Laundering': 'Financial',
    'Tax Offenses': 'Financial',
    'Antitrust Violations': 'Financial',
    'Bribery': 'Financial',
    'Auto Theft': 'Financial',
    'Burglary/Breaking and Entering': 'Financial',

    'Sexual Abuse': 'Sex',
    'Child Pornography (includes OFFTYPE2=42, Child Pornography)': 'Sex',
    'Gambling/Lottery': 'Sex',

    'Administration of Justice (Includes accessory after the fact, misprision of felony, and witness tampering)': 'Other',
    'Racketeering /Extortion': 'Other',
    'Prison Offenses': 'Other',
    'Civil Rights Offenses': 'Other',
    'National Defense Offenses': 'Other',
    'Environmental, Game, Fish, and Wildlife Offenses': 'Other',
    'Food and Drug Offenses': 'Other',
    'Traffic Violations and Other Offenses (Includes Other Drug, Environmental, Firearms, Miscellaneous Property Crimes, Violent, Traffic offenses, Obscenity, and Prostitution) (Includes OFFTYPE2= 43,44)': 'Other',
    None: 'Other'
}


